adding 1.8.0 formula
astronomer/homebrew-tap pull request #57
Opened 2022-11-22 18:09 UTC by kushalmalani

2022-11-22 18:12 UTC, neel-astro requested changes

2022-11-22 18:12 UTC, neel-astro commented on Formula/astro.rb
> +class AstroAT180 < Formula
```suggestion
class Astro < Formula
```

2022-11-22 18:13 UTC, kushalmalani commented on Formula/astro.rb
> +class AstroAT180 < Formula
yeah, just saw that...updated

2022-11-22 18:14 UTC, neel-astro approved these changes

2022-11-23 16:41 UTC, neel-astro approved these changes

2022-11-23 17:25 UTC, merged